In [1]:
import gym 
import random
import numpy as np 
import math
import time
# from IPython.display import clear_output

In [2]:
env = gym.make('FrozenLake-v0')

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [4]:
q_table

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [6]:
rewards_all_episodes = []

In [7]:
# Q-learning algorithm
for episode in range(num_episodes):
    # initialize new episode params
    state = env.reset()
    done = False
    rewards_current_episode = 0    

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()        
        # Take new action
        new_state, reward, done, info = env.step(action)
        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
        learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        # Set new state        
        state = new_state
        # Add new reward
        rewards_current_episode += reward 
        if done == True: 
            break
    # Exploration rate decay   
    exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    # Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)

In [8]:
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.1400000000000001
2000 :  0.5290000000000004
3000 :  0.5190000000000003
4000 :  0.5740000000000004
5000 :  0.6020000000000004
6000 :  0.6820000000000005
7000 :  0.6630000000000005
8000 :  0.6860000000000005
9000 :  0.6340000000000005
10000 :  0.6770000000000005


In [9]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[5.06874363e-01 4.77861230e-01 4.78696333e-01 4.77731155e-01]
 [3.75311702e-02 4.86051545e-02 6.70618135e-02 4.44311534e-01]
 [3.29871613e-01 1.21180765e-01 2.08074097e-01 2.00193067e-01]
 [4.87509055e-05 0.00000000e+00 5.36259961e-06 2.05253361e-01]
 [5.23396925e-01 3.31662219e-01 3.84829581e-01 2.66833892e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.61060966e-01 1.19167805e-01 1.71318885e-01 5.77313413e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.59000050e-01 3.05735147e-01 4.18014606e-01 5.50684059e-01]
 [4.41902921e-01 5.89461273e-01 4.67518658e-01 4.09221256e-01]
 [5.18338964e-01 2.26410499e-01 3.01831837e-01 2.69443919e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.41054001e-01 4.29533343e-01 6.83754759e-01 4.11954650e-01]
 [7.37101227e-01 8.68584446e-01 7.27144703e-01 7.05848358e-01]
 [0.00000000e+00 0.00000000e

In [10]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
#     time.sleep(1)

    for step in range(max_steps_per_episode):
#         clear_output(wait=True)
        env.render()
        action = np.argmax(q_table[state,:])        
        print(action)
        new_state, reward, done, info = env.step(action)
#         time.sleep(0.3)
        if done:
#             clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
#                 time.sleep(3)
            else:
                print("****You fell through a hole!****")
#                 time.sleep(3)
#                 clear_output(wait=True)
            break
        state = new_state
env.close()

*****EPISODE  1 *****





SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
3
  (Up)
SFFF
FHFH
FFFH
HFFG
1
  (Down)
SFFF
FHFH
FFFH
HFFG
2
  (Right)
SFFF
FHFH
FFFH
HFFG
1
  (Down)
SFFF
FHFH
FFFH
HFFG
1
  (Down)
SFFF
FHFH
FFFH
HFFG
2
  (Right)
SFFF
FHFH
FFFH
HFFG
1
  (Down)
SFFF
FHFH
FFFH
HFFG
2
  (Right)
SFFF
FHFH
FFFH
HFFG
2
  (Right)
SFFF
FHFH
FFFH
HFFG
1
  (Down)
SFFF
FHFH
FFFH
HFFG
1
  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
*****EPISODE  2 *****





SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (L